### ISSUE TITLE
combining nodemon with hmr

### ISSUE THREAD

**Issue by zcaudate** [Izhaki/nodemon-webpack-plugin#126]
I've been playing around with `react-blessed-hot-motion`
and it does something very similar to [this library](https://github.com/gaearon/react-blessed-hot-motion/blob/master/server.js#L50), though only restarting the app on a `running` flag and then deferring to [hmr](https://github.com/gaearon/react-blessed-hot-motion/blob/master/src/index.js#L29) for the hot code reloading.

is there a way to set this up currently with the plugin?

**Comment by Izhaki** [comment]
This is actually quite cool.

# Their's

Just for future reference, [here is the code from react-blessed-hot-motion](https://github.com/gaearon/react-blessed-hot-motion/blob/master/server.js#L50):

```
webpack(backendConfig).watch(100, function(err, stats) {
  if (!running) {
    running = true;
    nodemon({
      execMap: {
        js: 'node'
      },
      script: path.join(__dirname, 'build', 'backend'),
      ignore: ['*'],
      watch: ['foo/'],
      ext: 'noop'
    });
  }

  // There's a trick here. Restart will just send SIGUSR2 to our process.
  // src/signal.js will intercept it and handle hot update instead of restarting.

  nodemon.restart();
});
```

A few things to notice:

- It runs nodemon only once.
- It seems to ask nodemon to ignore all files (`ignore: ['*']`)
- Thereafter, when the (webpack) callback is called it only calls `nodemon.restart();`
- In [signal.js](https://github.com/gaearon/react-blessed-hot-motion/blob/master/src/signal.js) there is bespoke code to handle the `SIGUSR2` event.

# This plugin

- Also lunches nodemon only once.
- Will restart the watched process whenever a file changes in the watched path.

## Thoughts

- I've made every possible effort to keep this plugin simple and not to extend the nodemon api.
- This will only help cases where the process being watched support the `SIGUSR2` event, this will be a very small class of processes.
- When exactly should this plugin call `nodemon.restart();`? in `OnAfterEmit` (after Webpack emitted the files)?

This is not the first time I say it, but I think **there will be much more value for people if it is nodemon that supports this rather than only this plugin**. This way both nodemon users and this plugin can do what you are asking.

So I went and checked the nodemon repo and guess what? The [default config](https://github.com/remy/nodemon/blob/master/lib/config/defaults.js) has:

```
  signal: 'SIGUSR2'
```

So there's some good chance that nodemon does this already by default? Note that the code from `react-blessed-hot-motion` is 6 years old and nodemon may have changed a great deal since.

I would encourage you to post a similar question in the nodemon repo and see what answer you get there.

I'm keeping the issue open for now.

**Comment by zcaudate** [comment]
sweet. thanks for the explanation. I don't think I really understood webpack because I always thought it was a just cli but it's pretty cool what can be done with it as a library.

fyi..

I ended up dropping nodemon altogether and just doing the full restart while in dev via [run-node-webpack-plugin](https://github.com/rdoo/run-node-webpack-plugin) because when upgraded with newer versions, the ui was not rendering as expected with hmr and nodemon tended to not behave well with [mouse clicks](https://github.com/remy/nodemon/issues/890) within the terminal.

**Comment by Izhaki** [comment]
Closing based on response from Nodemon's author.
