### ISSUE TITLE
Only first entry in entry object is ran in nodemon

### ISSUE THREAD

**Issue by Townsheriff** [Izhaki/nodemon-webpack-plugin#144]
Hey,

Thanks for the plugin and it is working great!

My project has multiple entry points, but they are compiled in the same way and are using only one webpack config. For production I build all assets with one command and running transpiler, bundler only once per each "entry" object key. I want to have same behaviour when running locally for development, meaning 1 config file with multiple entry points.

development.config.js - desired config all entries (actually output asset paths are ran in separate nodomen process)
```
module.exports = {
  entry: {
     a: "./src/a.js",
     b: "./src/b.js"
  },
  output: {
      filename: "[name]/bundle.min.js",
  }
  ...
}
```

Workaround - running multiple `webpack --watch` processes with different condition env or cli.
```
const getEntry = () => {
  if (/* some condition  */) {
    return { a: "./src/a.js" };
  }
  
  return { b: "./src/b.js" }
};

module.exports = {
  entry: getEntry(),
  output: {
      // this is the actual file that will be watched
      filename: "[name]/bundle.min.js",
  },
  ...
}
```

Nodemon webpack plugin does not automatically detect multiple entries and run each in a separate process instead it picks the first on and runs only it. You can see this behvaiour [here](https://github.com/Izhaki/nodemon-webpack-plugin/blob/f756462682c21cf5287f4c9b40761c05d5a0c86f/src/webpack-utils.js#L7). Implementing a loop for [startMonitoring](https://github.com/Izhaki/nodemon-webpack-plugin/blob/master/src/index.js#L45) function would solve this issue.

Related tickets, but not exact behaviour explained here:
* [Having multiple Nodemon plugin instances](https://github.com/Izhaki/nodemon-webpack-plugin/issues/115)
* [How to use with multiple webpack configs](https://github.com/Izhaki/nodemon-webpack-plugin/issues/128)
* [How to set order of processing orders](https://github.com/webpack/webpack.js.org/issues/4685)

Cheers,
Arturs

**Comment by Izhaki** [comment]
Hello!

> Implementing a loop for [startMonitoring](https://github.com/Izhaki/nodemon-webpack-plugin/blob/master/src/index.js#L45) function would solve this issue.

## Won't Work

First, this will be a massive breaking change (tons of people using the plugin that have multiple entries would have all of them restarting - where you have no idea which entry needs restarting and which isn't).

A cleaner solution would be to allow passing an array to the [script option](https://github.com/Izhaki/nodemon-webpack-plugin#with-config).

This, however, will mean that this plugin breaks a key design principal where it only delegates to `nodemon`, without offering additional functionality.

Even if we would decide it is OK to have an array for the `scripts` option, it won't work [due to a limitation with nodemon described in the very issue you have mentioned](https://github.com/Izhaki/nodemon-webpack-plugin/issues/115#issuecomment-614281689).

# Solution

As proposed in https://github.com/Izhaki/nodemon-webpack-plugin/issues/115#issuecomment-831516263 you could write a simple script that starts and the two scripts you need to restart, and listens to `SIGTERM` in order to restart these (very much like [this](https://github.com/Izhaki/nodemon-webpack-plugin/blob/f756462682c21cf5287f4c9b40761c05d5a0c86f/src/index.js#L69-L71)). You don't have to have this script in your `dist` folder, it can be just any odd script in the repo. Just point the `script` option in the config object to it.

If you are using Node 14, you may save yourself some pain by using [Google's ZX](https://github.com/google/zx) to do most of the work, although just using node built-ins should not take much longer.

**Comment by Izhaki** [comment]
Closed due to inactivity.
