### ISSUE TITLE
Run npm commands for every changes

### ISSUE THREAD

**Issue by ujjwalguptaofficial** [Izhaki/nodemon-webpack-plugin#26]
Hi 

I am looking to run npm commands for every changes in code. Something like this - https://stackoverflow.com/questions/34588458/how-to-do-linting-using-nodemon

Here is my project link - https://github.com/ujjwalguptaofficial/fortjs-typescript-starter

**Comment by Izhaki** [comment]
Can you try:

```js
new NodemonPlugin({
    exec: ['npm', 'run', 'test']
})
```

**Comment by ujjwalguptaofficial** [comment]
When I am specifying - npm run lint . It is running - `npm run lint build\app.js`

![untitled](https://user-images.githubusercontent.com/10938615/50266162-a4c45f00-0448-11e9-87e8-ef86e48f87af.png)

Hope this helps you. You should download my repo and try it out yourself.

**Comment by Izhaki** [comment]
Right then. Per the SO question you have linked in the original post, the correct configuration is:

```
    exec: ['npm', 'run', 'lint', '&&', 'node']
```

Two things to note though:

First, I feel this is a bit hackey - don't think nodemon was designed for this. I'd opt of a tslint-loader or tslint-plugin for webpack instead for this task.

Second, at least on my machine (OS X) I have to change the npm script to:

```
"lint": "tslint 'src/**/*.ts'",
```

Putting the glob in quotation marks so tslint uses node glob rather than bash glob and pick up files in the `src` folder as well as subs (see [tsnode issue](https://github.com/palantir/tslint/pull/827)).
